spring.application.name=backend
server.port=8080
spring.profiles.active=dev

# DataSource Configuration
spring.datasource.driver-class-name=org.postgresql.Driver

# === JWT 설정 ===
jwt.secret=${JWT_SECRET}

# 브라우저에서 접근할 url패턴
spring.mvc.static-path-pattern=/**

# 실제 파일이 저장된 경로 , 뒤에 경로 적으면 우선순위가 적용됨
spring.web.resources.static-locations=file:./upload/, classpath:/static/
# spring.web.resources.static-locations=file:/home/young/www/ncafe/backend/upload/, classpath:/static/

# JPA 설정
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 파일 업로드 용량 제한 설정 (기본 1MB는 너무 작음)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# === 포트원 시크릿 설정 ===
portone.api-secret=hwA42FD6W5gc4o2aTYFqRMCHmaMdowtW2jBYtnXeqFFWpGJKDIbJWO4vSAq5GoOhSSo8nBhefZRoYVYe
