spring.application.name=backend
server.port=8031

# 1. Host를 localhost로 변경하고 포트는 5432 유지
spring.datasource.url=jdbc:postgresql://localhost:5432/ncafe
spring.datasource.username=ncafe
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# 브라우저에서 접근할 url패턴
spring.mvc.static-path-pattern=/**

# 실제 파일이 저장된 경로 , 뒤에 경로 적으면 우선순위가 적용됨
spring.web.resources.static-locations=file:./upload/, classpath:/static/
# spring.web.resources.static-locations=file:/home/young/www/ncafe/backend/upload/, classpath:/static/

# JPA/Hibernate 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
